travis:
  secure:
    BINSTAR_TOKEN: nc16UQKZaPZRd5Sumyphs8YGxOymR6RiDm1m7LZDlf9ESG4U/IH9gWbK2/ovX89OMt2tBnAWvmZ70ENvhs2VxRemb9FicsrZsvEEqTSbJ8EslIgR4S8cS0+L6ljvMWrvYjE57u9PFpTVmFXg5iunNI2cDAnFjRgpOTi0qWhpbVbdlIvNLFCcmw9dirBDAX3YFq6FBR7mGWt0MZNMY7b9bJFLTn9IA/8Umj5efYx7RREmD0jdd8UPR0R1i4fIL+VOyiGRR0f1i76attCM5sOypBzKr+9A3CC9anWCAT4n60QtD99spblxXF71uHhMEJO4dvnwEtod1C8qp+cBZEP4xUtxgtiF74pmc0ec5xPHj0BI/kE2IWIAU0vaKSA/pR2MnvgPXZBYsaT3LzsfdrVrdxCs5Omuo0MHAvoUHz2eEIxIRv3KwX4/kQnl+OxC+PE6nEojuIc6v5hrBwloGzAGK98G+5GVc8Irz/aOJwEhnDs8uf2E1404WiKoLaLhhkxcsWm0+M7yDE0J+EBPb4Ov9qPtZsDJ+1qrZNisdkQ40gAGZIlx5shrpIdkMJx3yC5fCp5CXnufdlNl6RwGnVqudcc68K8yPS5pBkvHM6RT+aY5VOteYZH3RaXIviWmlJqaoM0TbSPAKCUt61QnKt6aT2I3HTEvpLFQG8Fucu3cGEM=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
