travis:
  secure:
    BINSTAR_TOKEN: kgDOiUSEYFq81dM5rESTj8yQhRJOOUvuj4Kby1Z0azVRsjcv1jbb54EHI8iYG2kbi+b6UiB1/8Dp0tVcltmeCzVhjm8xJ36k10aEgx/IeXdVUHJ3mksVS5T7GhA3/XDy8RDl8IiYBvtjEiAYnI24zTcC7bzsWdoAVvNugYz+EN1Vis/MgwZCvkOsgz5kM4L7MJsSEllfcUxRoELQwsvk2buaCbKorbIXO/uMh2vR9qKm7fpvdZA/gVUYaY/oWLYaRM3+NiAn6VnxQPjC95ujoOoOZM50KTFZEVjacCKGLH0NrA1xhHs4YA4gaVhdLN1lhy4s9Sg02H0M0A45QkiOWlKaqErUL7FLSWs/rdam4cU+a5Cjx00lPs5ahqPLekm5CvunIdn1jd3VJHkZX3ZTN1oKKP4o1/t4IeoAAdceBTfBpBcXkvfqdc6pgeZQTlM1/tPS8nsor66F1xHjLDNNFDk0B2fWL93ZWRrqhuiFlgosBULiYtxsXrmqTLmzylTRPPc44yh+N12IRaTaWpn+hJvsfAz0Hdlsf5d5t8tne3ouOBcYqjYRWuLRCXxp8fla9/8BWBsq27Xw88RimISB+LADOSl+cMCn/SYIdM5jrfrTyMaMjnun5kA8QRqo8dobIJqmnbVwNOcH7f3bdQJPzBcPUzw3fmJwBsyG/vB25mQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
