travis:
  secure:
    BINSTAR_TOKEN: Z6goO3IF5cq3eKG4QiQKV3xVZbnVC7OzpybPqFy6r9pk9bsco7ComMWoq9D48pGkpzfOajP1VAgdiFYEbvT985QREtclRFY87vGyuZHJ7Tp+PbTVUektLqzoFQ8qGis+y026jcStoyHLdL1nwYvEq+RUVm+9G4HiQafCFBBHLS3R15HGhzHn5uHQIj32Qp8AGXkdQSEtSgTwhp74LN/rdA71MX1cjvJV1ro8WIucLhJYR8W1VqKdNRe1hwRjSvFzfThDY7meZEidkLJC82a/xsl03Wh2EfBPDitjFwL8/hC7/OgoZaU8ZuwtolVUzhuyQtuDwGhvQbXpSAtiThJ6Dl2O0HPcC4EyiXphAyeqN9YD6+9AQAY9JjgYYjarir5IAgrr56fb48qyseBmfYs1ik+8z2URFN//SwF5KafHynD4tHfLPDDk8IMfoWDPRv8m33Zih7SONPnPYjocs3ni4tbC7/3/k+y1k4Le4d9Hweh6qvPXhNrscR9SeFW2unFVHloHyUo5hzSF/5o/Iz4G3Y4SjXkmhDl+hr5f0094AuQivfXfQjhU9bDvNwlllEN6+410o8uGdgxKWadvUMot/SwWogoiadgYfs6H2HhIVV6RbSeiFLNKgjp1vRuu2wjWgL8q3bLWxuulHTP3S+lSbquzvt2Ghh/MBmpD1xcGErw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
