travis:
  secure:
    BINSTAR_TOKEN: d620I+hUMyti5xJU2h+WIsVn2FXJ0hLsNkJK2Y5SCEhTCSQloyV+IilkzKFipRSLUg9poYMQ5OLt7DA/6UmRXvIKY++6Cgg7ha/Lb2EoHvq/Z6/INRLwAxY4lnPcf/gD3tPuuKjjTUmRCgmvAuLDIB8ZavL+y/9sGb6ft7RzUqDX89R0WSlFddB8FaRP36sJVH7MrU6aWrFEU/mwiiFa9uWVjXS6VjBLuQuLGjPHpJWAXH01Mi7o3Ld2HrFKP3BGOPyztMlRpdJeb3FDKnPj3Qb+b6MfmTSG76DyHfN7qjI78CIISh8Zl6gJKhFbXjaeXaJVTgLjqSYRSInUA7r+5jCei3Sjdjn7iAAvVwKeOad+NUPzy32lql0ZrblMmr7zxjBdf8gB5GSQXCHvVVReQRBlq9MsHGvqb6bnZpDrqDKkSb3b6vaL74c/du5P8iW+f0rHxxPop+Ld99wLn416OWMdkrLz0W38un39G2ieW2CEfT27kOvnvHjLu7/sd9b47hhvlj2eZucyrYRTrIkx+o5b+pH3sGfsCoPfRii5rSiYafHrsylpPkfTRCbbb6ZVgLV4sDzsSS4PGNYuy8NljiVbhO01udVCWVhr1CqHQGgqpIONCvXRUTERAo2wQJTOu/0Ir+JlvJKP0PB5ygvIUKmNQx740eZGXlyI8tjaHXc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
